import { Component, OnInit, input, inject, signal, DestroyRef } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { finalize, switchMap, tap } from 'rxjs/operators';

import { InputComponent } from '../../shared/input/input.component';
import { 
  WorkCaseService, 
  InvoiceService, 
  WorkCaseItemResponse, 
  InvoiceDetailResponse,
  UpdateInvoiceCommand 
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-invoice-edit',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslatePipe, RouterLink, InputComponent],
  templateUrl: './invoice-edit.component.html',
  styleUrls: ['./invoice-edit.component.scss']
})
export class InvoiceEditComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly workCaseService = inject(WorkCaseService);
  private readonly invoiceService = inject(InvoiceService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly notation = inject(NotificationService);
  public readonly id = input.required<string>();
  private readonly location = inject(Location);

  public invoice = signal<InvoiceDetailResponse | null>(null);
  public items = signal<WorkCaseItemResponse[]>([]);
  public selectedItemIds = signal<string[]>([]);
  public originalItemIds = signal<string[]>([]);
  public isLoading = signal<boolean>(true);
  public isSaving = signal<boolean>(false);

  public invoiceForm!: FormGroup;

  ngOnInit(): void {
    this.initForm();
    this.loadInvoiceData();
  }

  private initForm(): void {
    this.invoiceForm = this.fb.group({
      issueDate: ['', Validators.required],
      serviceDate: ['', Validators.required],
      taxRate: [23, [Validators.required, Validators.min(0), Validators.max(100)]],
      targetCurrency: ['PLN', Validators.required],
      manualExchangeRate: [null, Validators.min(0)]
    });
  }

  private loadInvoiceData(): void {
    this.isLoading.set(true);
    
    this.invoiceService.getInvoiceById(this.id()).pipe(
      tap(invoice => {
        this.invoice.set(invoice);
        
        const originalIds = invoice.items?.map(i => i.itemId!).filter(id => !!id) || [];
        this.originalItemIds.set(originalIds);
        this.selectedItemIds.set([...originalIds]);
        
        this.invoiceForm.patchValue({
          issueDate: invoice.issueDateUtc ? new Date(invoice.issueDateUtc as string).toISOString().substring(0, 10) : '',
          serviceDate: invoice.serviceDateUtc ? new Date(invoice.serviceDateUtc as string).toISOString().substring(0, 10) : '',
          taxRate: invoice.tax,
          targetCurrency: invoice.currency
        });
      }),
      switchMap(invoice => this.workCaseService.getItemsForWorkCase(invoice.workCaseId!)),
      finalize(() => this.isLoading.set(false)),
      takeUntilDestroyed(this.destroyRef)
    ).subscribe({
      next: (allItems) => {
        const availableItems = allItems.filter(x => !x.isInvoiced || x.invoiceId === this.id());
        this.items.set(availableItems);
      },
      error: (err) => this.notation.apiError(err)
    });
  }

  public toggleItemSelection(itemId: string | undefined): void {
    if (!itemId) return;

    const currentSelected = this.selectedItemIds();
    if (currentSelected.includes(itemId)) {
      this.selectedItemIds.set(currentSelected.filter(id => id !== itemId));
    } else {
      this.selectedItemIds.set([...currentSelected, itemId]);
    }
  }

  public abandonInvoice(): void {
    if (confirm('GUI.INVOICE.ABANDON_QUESTION')) {
      this.isSaving.set(true);
      this.invoiceService.abandonInvoice(this.id())
        .pipe(
          finalize(() => this.isSaving.set(false)),
          takeUntilDestroyed(this.destroyRef)
        )
        .subscribe({
          next: () => {
            this.notation.success('GUI.INVOICE.ABANDON_SUCCESS');
            this.router.navigate(['/dashboard/workcase', this.invoice()?.workCaseId]);
          },
          error: (err) => this.notation.apiError(err)
        });
    }
  }

  public onSubmit(): void {
    if (this.invoiceForm.invalid) {
      this.invoiceForm.markAllAsTouched();
      return;
    }

    if (this.selectedItemIds().length === 0) {
        this.notation.apiError('GUI.INVOICE.NO_ITEMS_SELECTED');
        return;
    }

    this.isSaving.set(true);
    const formValue = this.invoiceForm.value;
    const itemsToDetach = this.originalItemIds().filter(id => !this.selectedItemIds().includes(id));

    const command: UpdateInvoiceCommand = {
      invoiceId: this.id(),
      issueDate: new Date(formValue.issueDate).toISOString(),
      serviceDate: new Date(formValue.serviceDate).toISOString(),
      taxRate: formValue.taxRate,
      targetCurrency: formValue.targetCurrency,
      manualExchangeRate: formValue.manualExchangeRate,
      workCaseItemIds: this.selectedItemIds(),
      workCaseItemsToDetachIds: itemsToDetach
    };

    this.invoiceService.updateInvoice(command)
      .pipe(
        finalize(() => this.isSaving.set(false)),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe({
        next: () => {
          this.notation.success('GUI.INVOICE.UPDATE_SUCCESS');
          this.location.back();
        },
        error: (err) => this.notation.apiError(err)
      });
  }
    public onCancel(): void {
      this.location.back();
    }
}