import { Component, OnInit, input, inject, signal, DestroyRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { finalize } from 'rxjs/operators';

import { InputComponent } from '../../shared/input/input.component';
import { 
  WorkCaseService, 
  InvoiceService, 
  WorkCaseItemResponse, 
  CreateInvoiceCommand 
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-invoice-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslatePipe, RouterLink, InputComponent],
  templateUrl: './invoice-create.component.html',
  styleUrls: ['./invoice-create.component.scss']
})
export class InvoiceCreateComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly workCaseService = inject(WorkCaseService);
  private readonly invoiceService = inject(InvoiceService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly notation = inject(NotificationService);

  public readonly id = input.required<string>();

  public items = signal<WorkCaseItemResponse[]>([]);
  public selectedItemIds = signal<string[]>([]);
  
  public isLoading = signal<boolean>(true);
  public isSaving = signal<boolean>(false);

  public invoiceForm!: FormGroup;

  ngOnInit(): void {
    this.initForm();
    this.loadItems();
  }

  private initForm(): void {
    const today = new Date().toISOString().substring(0, 10);
    
    this.invoiceForm = this.fb.group({
      serviceDate: [today, Validators.required],
      taxRate: [23, [Validators.required, Validators.min(0), Validators.max(100)]],
      targetCurrency: ['PLN', Validators.required],
      isPaid: [false],
      manualExchangeRate: [null, Validators.min(0)]
    });
  }

  private loadItems(): void {
    this.isLoading.set(true);
    this.workCaseService.getItemsForWorkCase(this.id())
      .pipe(
        finalize(() => this.isLoading.set(false)),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe({
        next: (data) => {
          const availableItems = data.filter(x => !x.isInvoiced);
          this.items.set(availableItems);
          
          const allIds = availableItems.map(x => x.id!).filter(id => !!id);
          this.selectedItemIds.set(allIds);
        },
        error: (err) => this.notation.apiError(err)
      });
  }

  public toggleItemSelection(itemId: string | undefined): void {
    if (!itemId) return;

    const currentSelected = this.selectedItemIds();
    if (currentSelected.includes(itemId)) {
      this.selectedItemIds.set(currentSelected.filter(id => id !== itemId));
    } else {
      this.selectedItemIds.set([...currentSelected, itemId]);
    }
  }

  public onSubmit(): void {
    if (this.invoiceForm.invalid) {
      this.invoiceForm.markAllAsTouched();
      return;
    }

    if (this.selectedItemIds().length === 0) {
      this.notation.apiError('GUI.INVOICE.NO_ITEMS_SELECTED');
      return;
    }

    this.isSaving.set(true);
    const formValue = this.invoiceForm.value;

    const command: CreateInvoiceCommand = {
      workCaseId: this.id(),
      serviceDate: new Date(formValue.serviceDate).toISOString(),
      taxRate: formValue.taxRate,
      targetCurrency: formValue.targetCurrency,
      isPaid: false,
      manualExchangeRate: formValue.manualExchangeRate,
      workCaseItemIds: this.selectedItemIds()
    };

    this.invoiceService.createInvoice(command)
      .pipe(
        finalize(() => this.isSaving.set(false)),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe({
        next: () => {
          this.notation.success('GUI.INVOICE.CREATE_SUCCESS');
          this.router.navigate(['/dashboard/workcase', this.id()]);
        },
        error: (err) => this.notation.apiError(err)
      });
  }
}