import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, FormsModule, Validators } from '@angular/forms';
import { catchError, of, tap } from 'rxjs';
import { TranslatePipe } from '@ngx-translate/core';

import { 
  ServiceContractorResponse,
  CreateServiceContractorCommand,
  UpdateServiceContractorCommand,
  ServiceContractorService 
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { InputComponent } from '../../shared/input/input.component';

@Component({
  selector: 'app-service-contractors',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, TranslatePipe, InputComponent],
  templateUrl: './service-contractors.component.html',
  styleUrl: './service-contractors.component.scss'
})
export class ServiceContractorsComponent {
  private fb = inject(FormBuilder);
  private apiClient = inject(ServiceContractorService);
  private notation = inject(NotificationService);

  public contractors = signal<ServiceContractorResponse[]>([]);
  public selectedContractor = signal<ServiceContractorResponse | null>(null);
  
  public isCreateMode = signal<boolean>(false);
  public isLoading = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  
  public pageNumber = signal<number>(1);
  public totalPagesNumber = signal<number>(1);
  public pageSize = signal<number>(100);

  public filters = {
    name: '',
    tax: '',
    city: '',
    country: '',
    isActive: undefined as boolean | undefined
  };

  public contractorForm: FormGroup;

  constructor() {
    this.contractorForm = this.fb.group({
      id: [{ value: '', disabled: true }],
      name: ['', Validators.required],
      tax: ['', Validators.required],
      country: ['', Validators.required],
      city: ['', Validators.required],
      zip: ['', Validators.required],
      street: ['', Validators.required],
      houseNumber: ['', Validators.required],
      apartmentNumber: [null],
      email: ['', Validators.email],
      phoneNumber: [''],
      isActive: [true]
    });

    this.loadContractors();
  }

  public loadContractors() {
    this.isLoading.set(true);
    
    const name = this.filters.name.trim() || undefined;
    const tax = this.filters.tax.trim() || undefined;
    const city = this.filters.city.trim() || undefined;
    const country = this.filters.country.trim() || undefined;
    const isActive = this.filters.isActive ? true : undefined;

    this.apiClient.getServiceContractors(this.pageNumber(), this.pageSize(), name, tax, city, country, isActive)
      .pipe(
        tap(res => {
          this.contractors.set(res.items || []);
          this.isLoading.set(false);
          this.totalPagesNumber.set(res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1);
        }),
        catchError((error) => {
          this.notation.apiError(error);
          this.isLoading.set(false);
          return of({ items: [], totalCount: 0 });
        })
      ).subscribe();
  }

  public onSearch() {
    this.pageNumber.set(1);
    this.loadContractors();
  }

  public changePage(newPage: number) {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadContractors();
  }

  public onPageSizeChange(event: Event) {
    const selectElement = event.target as HTMLSelectElement;
    this.pageSize.set(Number(selectElement.value));
    this.pageNumber.set(1);
  }

  public selectContractor(contractor: ServiceContractorResponse) {
    this.isCreateMode.set(false);
    this.selectedContractor.set(contractor);
    
    this.contractorForm.patchValue({
      id: contractor.id,
      name: contractor.name,
      tax: contractor.tax,
      country: contractor.country,
      city: contractor.city,
      zip: contractor.zip,
      street: contractor.street,
      houseNumber: contractor.houseNumber,
      apartmentNumber: contractor.apartmentNumber,
      email: contractor.email,
      phoneNumber: contractor.phoneNumber,
      isActive: contractor.isActive ?? true
    });
  }

  public initCreateContractor() {
    this.selectedContractor.set(null);
    this.isCreateMode.set(true);
    
    this.contractorForm.reset({
      id: '',
      name: '',
      tax: '',
      country: '',
      city: '',
      zip: '',
      street: '',
      houseNumber: '',
      apartmentNumber: null,
      email: '',
      phoneNumber: '',
      isActive: true
    });
  }

  public toggleTripleState() {
    if (this.filters.isActive === undefined) {
      this.filters.isActive = true;
    } else if (this.filters.isActive === true) {
      this.filters.isActive = false;
    } else {
      this.filters.isActive = undefined;
    }
  }

  public onSubmit() {
    if (this.contractorForm.invalid) return;
    if (!this.isCreateMode() && !this.selectedContractor()) return;

    this.isSaving.set(true);
    const formValues = this.contractorForm.getRawValue();

    if (this.isCreateMode()) {
      const command: CreateServiceContractorCommand = {
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber || null,
        email: formValues.email || null,
        phoneNumber: formValues.phoneNumber || null,
        isActive: formValues.isActive
      };

      this.apiClient.addServiceContractor(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.isCreateMode.set(false);
          this.loadContractors();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });

    } else {
      const command: UpdateServiceContractorCommand = {
        id: this.selectedContractor()!.id,
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber || null,
        email: formValues.email || null,
        phoneNumber: formValues.phoneNumber || null,
        isActive: formValues.isActive
      };

      this.apiClient.editServiceContractor(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.loadContractors();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
    }
  }
}