import { Component, inject, signal, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, FormArray, ReactiveFormsModule, FormsModule, Validators, AbstractControl } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';

import { 
  ServiceContractorResponse,
  CreateServiceContractorCommand,
  UpdateServiceContractorCommand,
  ServiceContractorService 
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { InputComponent } from '../../shared/input/input.component';
import { ServiceContractorListSelectorComponent } from '../service-contractors-list-selector/service-contractors-list-selector.component';

@Component({
  selector: 'app-service-contractors',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, TranslatePipe, InputComponent, ServiceContractorListSelectorComponent],
  templateUrl: './service-contractors.component.html',
  styleUrl: './service-contractors.component.scss'
})
export class ServiceContractorsComponent {
  private fb = inject(FormBuilder);
  private apiClient = inject(ServiceContractorService);
  private notation = inject(NotificationService);

  @ViewChild(ServiceContractorListSelectorComponent) 
  public listSelector!: ServiceContractorListSelectorComponent;

  public selectedContractor = signal<ServiceContractorResponse | null>(null);
  public isCreateMode = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  
  public contractorForm: FormGroup;

  get bankAccountsFormArray(): FormArray {
    return this.contractorForm.get('bankAccounts') as FormArray;
  }

  constructor() {
    this.contractorForm = this.buildForm();
  }

  private buildForm(): FormGroup {
    return this.fb.group({
      id: [{ value: '', disabled: true }],
      name: ['', Validators.required],
      tax: ['', Validators.required],
      country: ['', Validators.required],
      city: ['', Validators.required],
      zip: ['', Validators.required],
      street: ['', Validators.required],
      houseNumber: ['', Validators.required],
      apartmentNumber: [null],
      email: ['', [Validators.email]],
      phoneNumber: [''],
      isActive: [true],
      bankAccounts: this.fb.array([])
    });
  }

  public selectContractor(contractor: ServiceContractorResponse) {
    this.isCreateMode.set(false);
    this.selectedContractor.set(contractor);
    this.clearBankAccounts();

    this.contractorForm.patchValue({
      id: contractor.id,
      name: contractor.name,
      tax: contractor.tax,
      country: contractor.country,
      city: contractor.city,
      zip: contractor.zip,
      street: contractor.street,
      houseNumber: contractor.houseNumber,
      apartmentNumber: contractor.apartmentNumber,
      email: contractor.email,
      phoneNumber: contractor.phoneNumber,
      isActive: contractor.isActive ?? true
    });

    if (contractor.bankAccounts && contractor.bankAccounts.length > 0) {
      contractor.bankAccounts.forEach(account => {
        this.bankAccountsFormArray.push(this.createBankAccountGroup(account));
      });
    }

    this.contractorForm.markAsPristine();
    this.contractorForm.markAsUntouched();
  }

  public initCreateContractor() {
    this.selectedContractor.set(null);
    this.isCreateMode.set(true);
    this.clearBankAccounts();
    this.contractorForm.reset({
      id: '',
      name: '',
      tax: '',
      country: '',
      city: '',
      zip: '',
      street: '',
      houseNumber: '',
      apartmentNumber: null,
      email: '',
      phoneNumber: '',
      isActive: true
    });

    this.addBankAccount();

    this.contractorForm.markAsPristine();
    this.contractorForm.markAsUntouched();
  }

  // --- LOGIKA KONT BANKOWYCH ---

  public asFormGroup(control: AbstractControl): FormGroup {
    return control as FormGroup;
  }

  private clearBankAccounts() {
    while (this.bankAccountsFormArray.length !== 0) {
      this.bankAccountsFormArray.removeAt(0);
    }
  }

  private createBankAccountGroup(account?: any): FormGroup {
    return this.fb.group({
      id: [account?.id || null],
      bankName: [account?.bankName || '', Validators.required],
      iban: [account?.iban || '', Validators.required],
      currencyCode: [account?.currencyCode || 'PLN', Validators.required],
      isMain: [account?.isMain || false]
    });
  }

  public addBankAccount() {
    const isFirst = this.bankAccountsFormArray.length === 0;
    this.bankAccountsFormArray.push(this.createBankAccountGroup({ isMain: isFirst }));
  }

  public removeBankAccount(index: number) {
    const isMain = this.bankAccountsFormArray.at(index).get('isMain')?.value;
    this.bankAccountsFormArray.removeAt(index);
    
    if (isMain && this.bankAccountsFormArray.length > 0) {
      this.setMainAccount(0);
    }
  }

  public setMainAccount(index: number) {
    this.bankAccountsFormArray.controls.forEach((control, i) => {
      control.get('isMain')?.setValue(i === index);
    });
  }

  public onSubmit() {
    if (this.contractorForm.invalid) {
      this.contractorForm.markAllAsTouched();
      return;
    }
    if (!this.isCreateMode() && !this.selectedContractor()) return;

    this.isSaving.set(true);
    const formValues = this.contractorForm.getRawValue();

    const bankAccountsPayload = formValues.bankAccounts.map((a: any) => ({
      id: a.id ? a.id : null,
      bankName: a.bankName,
      iban: a.iban,
      currencyCode: a.currencyCode,
      isMain: a.isMain
    }));

    if (this.isCreateMode()) {
      const command: CreateServiceContractorCommand = {
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber || null,
        email: formValues.email || null,
        phoneNumber: formValues.phoneNumber || null,
        isActive: formValues.isActive,
        bankAccounts: bankAccountsPayload
      };

      this.apiClient.addServiceContractor(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.isCreateMode.set(false);
          this.listSelector.loadContractors(); 
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });

    } else {
      const command: UpdateServiceContractorCommand = {
        id: this.selectedContractor()!.id,
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber || null,
        email: formValues.email || null,
        phoneNumber: formValues.phoneNumber || null,
        isActive: formValues.isActive,
        bankAccounts: bankAccountsPayload
      };

      this.apiClient.editServiceContractor(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.listSelector.loadContractors(); 
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
    }
  }
}