import { Component, inject, signal, OnInit, Output, EventEmitter, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { catchError, of, tap } from 'rxjs';
import { ClientService, ClientListItemResponse } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-client-list-selector',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslatePipe],
  templateUrl: './client-list-selector.component.html',
  styleUrl: './client-list-selector.component.scss'
})
export class ClientListSelectorComponent implements OnInit {
  private apiClient = inject(ClientService);
  private notation = inject(NotificationService);

  public activeClient = input<ClientListItemResponse | null>(null);
  public showAddButton = input<boolean>(true);
  public clientSelected = output <ClientListItemResponse>();
  public addRequested = output <void>();

  public clients = signal<ClientListItemResponse[]>([]);
  public isLoading = signal<boolean>(false);
  public pageNumber = signal<number>(1);
  public totalPagesNumber = signal<number>(1);
  public pageSize = signal<number>(100);

  public filters = {
    name: '',
    tax: '',
    city: '',
    country: '',
    isActive: undefined as boolean | undefined
  };

  ngOnInit(): void {
    this.loadClients();
  }

  public loadClients(): void {
    this.isLoading.set(true);
    
    const name = this.filters.name.trim() || undefined;
    const tax = this.filters.tax.trim() || undefined;
    const street = undefined;
    const zip = undefined;
    const country = this.filters.country.trim() || undefined;
    
    const isActive = (this.filters.isActive === true || this.filters.isActive === false) 
      ? this.filters.isActive 
      : undefined;

    this.apiClient.getClients(tax, name, street, zip, country, this.pageNumber(), this.pageSize(), isActive)
      .pipe(
        tap(res => {
          this.clients.set(res.items || []);
          this.isLoading.set(false);
          this.totalPagesNumber.set(res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1);
        }),
        catchError((error) => {
          this.notation.apiError(error);
          this.isLoading.set(false);
          return of({ items: [], totalCount: 0 });
        })
      ).subscribe();
  }

  public onSearch(): void {
    this.pageNumber.set(1);
    this.loadClients();
  }

  public changePage(newPage: number): void {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadClients();
  }

  public onPageSizeChange(event: Event): void {
    const inputElement = event.target as HTMLInputElement;
    this.pageSize.set(Number(inputElement.value));
    this.pageNumber.set(1);
    this.loadClients();
  }

  public toggleTripleState(): void {
    if (this.filters.isActive === undefined) {
      this.filters.isActive = true;
    } else if (this.filters.isActive === true) {
      this.filters.isActive = false;
    } else {
      this.filters.isActive = undefined;
    }
  }

  public selectClient(client: ClientListItemResponse): void {
    this.clientSelected.emit(client);
  }

  public requestAdd(): void {
    this.addRequested.emit();
  }
}