import { Component, inject, signal, OnInit, DestroyRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

import { InputComponent } from '../../shared/input/input.component';
import { ClientListSelectorComponent } from '../../clients/client-list-selector/client-list-selector.component';
import { WorkCaseService, CreateWorkCaseCommand, ClientDetailResponse } from '../../_services/autogenerated/autogenerated.service';
import { AuthService } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-work-case-add',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslatePipe, RouterLink, InputComponent, ClientListSelectorComponent],
  templateUrl: './work-case-add.component.html',
  styleUrls: ['./work-case-add.component.scss']
})
export class WorkCaseAddComponent implements OnInit {
  private fb = inject(FormBuilder);
  private router = inject(Router);
  private workCaseService = inject(WorkCaseService);
  private authService = inject(AuthService); 
  private destroyRef = inject(DestroyRef);
  private notation = inject(NotificationService);
  
  selectedClient = signal<ClientDetailResponse | null>(null);
  isClientActive = signal<boolean | null>(null);
  isSaving = signal<boolean>(false);
  
  workCaseForm!: FormGroup;

  ngOnInit(): void {
    this.initForm();
    this.loadCurrentUserAsForwarder();
  }

  private initForm(): void {
    this.workCaseForm = this.fb.group({
      relation: ['SE', Validators.required],
      amount: [0, [Validators.required, Validators.min(0)]],
      currencyCode: ['PLN', Validators.required],
      clientId: ['', Validators.required],
      forwarderId: ['', Validators.required]
    });
  }

  private loadCurrentUserAsForwarder(): void {
    this.authService.getCurrentUser()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (user) => {
          if (user && user.id) {
            this.workCaseForm.patchValue({ forwarderId: user.id });
          }
        },
        error: (err) => {
          this.notation.apiError(err);
        }
      });
  }

  onClientSelected(client: ClientDetailResponse): void {
    this.selectedClient.set(client);
    this.isClientActive.set(client.isActive === true)
    this.workCaseForm.patchValue({ clientId: client.id });
    this.workCaseForm.get('clientId')?.markAsDirty();
  }

  onSubmit(): void {
    if (this.workCaseForm.invalid || this.isSaving()) return;

    this.isSaving.set(true);

    const command: CreateWorkCaseCommand = this.workCaseForm.value;
    
    this.workCaseService.addWorkCase(command)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.notation.success('GUI.WORK_CASES.CREATE_SUCCESS');
          this.isSaving.set(false);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
  }
}