import { Component, inject, signal, OnInit, DestroyRef, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { finalize } from 'rxjs/operators';

import { InputComponent } from '../../shared/input/input.component';
import { ClientListSelectorComponent } from '../../clients/client-list-selector/client-list-selector.component';
import {
  WorkCaseService,
  UpdateWorkCaseCommand,
  ClientResponse,
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-work-case-edit',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    TranslatePipe,
    RouterLink,
    InputComponent,
    ClientListSelectorComponent,
  ],
  templateUrl: './work-case-edit.component.html',
  styleUrls: ['./work-case-edit.component.scss'],
})
export class WorkCaseEditComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly workCaseService = inject(WorkCaseService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly notation = inject(NotificationService);

  public readonly id = input.required<string>();

  public readonly isLoading = signal<boolean>(true);
  public readonly isSaving = signal<boolean>(false);
  public readonly selectedClient = signal<ClientResponse | null>(null);
  public readonly isClientActive = signal<boolean | null>(null);
  public readonly workCaseName = signal<string>('');

  public readonly workCaseForm = this.fb.group({
    workCaseId: ['', Validators.required],
    relation: ['', Validators.required],
    amount: [0, [Validators.required, Validators.min(0)]],
    currencyCode: ['', Validators.required],
    clientId: ['', Validators.required],
    forwarderId: ['', Validators.required],
  });

  ngOnInit(): void {
    this.loadWorkCaseData();
  }

  public onClientSelected(client: ClientResponse): void {
    this.selectedClient.set(client);
    this.isClientActive.set(client.isActive === true);
    this.workCaseForm.patchValue({ clientId: client.id });
    this.workCaseForm.get('clientId')?.markAsDirty();
  }

  public onSubmit(): void {
    if (this.workCaseForm.invalid || this.isSaving() || !this.isClientActive()) return;

    this.isSaving.set(true);
    const command = this.workCaseForm.getRawValue() as UpdateWorkCaseCommand;

    this.workCaseService
      .editWorkCase(command)
      .pipe(
        finalize(() => this.isSaving.set(false)),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe({
        next: () => {
          this.notation.success('GUI.EDIT_SUCCESS');
          this.router.navigate(['/dashboard/workcase', this.id()]);
        },
        error: (err) => this.notation.apiError(err),
      });
  }

  private loadWorkCaseData(): void {
    this.isLoading.set(true);

    this.workCaseService
      .getWorkCaseById(this.id())
      .pipe(
        finalize(() => this.isLoading.set(false)),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe({
        next: (data) => {
          this.workCaseName.set(data.name ?? 'Undefined');

          if (data.clientResponse && data.clientResponse.isActive) {
            this.selectedClient.set(data.clientResponse);
            this.isClientActive.set(data.clientResponse.isActive);
          }

          this.workCaseForm.patchValue({
            workCaseId: data.id,
            relation: data.relation,
            amount: data.amount,
            currencyCode: data.currency,
            clientId: data.clientId,
            forwarderId: data.forwarderId,
          });
        },
        error: (err) => this.notation.apiError(err),
      });
  }
}