import { Component, inject, signal, OnInit, DestroyRef, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

import { InputComponent } from '../../shared/input/input.component';
import { ClientListSelectorComponent } from '../../shared/client-list-selector/client-list-selector.component';
import { WorkCaseService, UpdateWorkCaseCommand, WorkCaseDetailsResponse, ClientDetailResponse } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-work-case-edit',
  standalone: true,
  imports: [
    CommonModule, 
    ReactiveFormsModule, 
    TranslatePipe, 
    RouterLink, 
    InputComponent, 
    ClientListSelectorComponent
  ],
  templateUrl: './work-case-edit.component.html',
  styleUrls: ['./work-case-edit.component.scss']
})
export class WorkCaseEditComponent implements OnInit {
  private fb = inject(FormBuilder);
  private router = inject(Router);
  private workCaseService = inject(WorkCaseService);
  private destroyRef = inject(DestroyRef);
  private notation = inject(NotificationService);

  // Pobieramy ID bezpośrednio ze ścieżki
  id = input.required<string>();
  
  workCaseForm!: FormGroup;
  isLoading = signal<boolean>(true);
  isSaving = signal<boolean>(false);
  
  // Sygnały tożsame z komponentem Add
  selectedClient = signal<ClientDetailResponse | null>(null);
  isClientActive = signal<boolean | null>(null);
  workCaseName = signal<string>('');

  ngOnInit(): void {
    this.initForm();
    this.loadWorkCaseData();
  }

  private initForm(): void {
    this.workCaseForm = this.fb.group({
      workCaseId: ['', Validators.required],
      relation: ['', Validators.required],
      amount: [0, [Validators.required, Validators.min(0)]],
      currencyCode: ['', Validators.required],
      clientId: ['', Validators.required],
      forwarderId: ['', Validators.required]
    });
  }

  private loadWorkCaseData(): void {
    this.isLoading.set(true);

    this.workCaseService.getWorkCaseById(this.id())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data: WorkCaseDetailsResponse) => {
          this.workCaseName.set(data.name ?? 'Undefined');
          
          // Mapujemy podstawowe dane klienta z odpowiedzi, by zasilić widok selektora
          const initialClient: Partial<ClientDetailResponse> = {
            id: data.clientId,
            name: data.clientName,
            isActive: !data.isAbandoned // Zakładamy aktywność na podstawie braku porzucenia lub true
          };
          
          this.selectedClient.set(initialClient as ClientDetailResponse);
          this.isClientActive.set(!data.isAbandoned);

          this.workCaseForm.patchValue({
            workCaseId: data.id,
            relation: data.relation,
            amount: data.amount,
            currencyCode: data.currency,
            clientId: data.clientId,
            forwarderId: data.forwarderId
          });
          
          this.isLoading.set(false);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isLoading.set(false);
        }
      });
  }

  onClientSelected(client: ClientDetailResponse): void {
    this.selectedClient.set(client);
    this.isClientActive.set(client.isActive === true);
    this.workCaseForm.patchValue({ clientId: client.id });
    this.workCaseForm.get('clientId')?.markAsDirty();
  }

  onSubmit(): void {
    if (this.workCaseForm.invalid || this.isSaving() || !this.isClientActive()) return;

    this.isSaving.set(true);
    const command: UpdateWorkCaseCommand = this.workCaseForm.value;
    
    this.workCaseService.editWorkCase(command)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.notation.success('GUI.WORK_CASES.EDIT_SUCCESS');
          this.isSaving.set(false);
          this.router.navigate(['/dashboard/workcase', this.id()]);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
  }
}