import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { InvoiceDetailResponse, InvoiceService } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-invoice-list',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslatePipe, RouterLink],
  templateUrl: './invoice-list.component.html',
  styleUrls: ['./invoice-list.component.scss']
})
export class InvoiceListComponent implements OnInit {
  private apiClient = inject(InvoiceService);
  private notation = inject(NotificationService);

  public pageNumber = signal<number>(1);
  public pageSize = signal<number>(50);
  public totalCount = signal<number>(0);
  public isLoading = signal<boolean>(false);
  public invoices = signal<InvoiceDetailResponse[]>([]);

  public totalPagesNumber = computed(() => Math.max(1, Math.ceil(this.totalCount() / this.pageSize())));

  public filters: {
    relation?: string;
    clientId?: string;
    forwarderId?: string;
    taxRate?: number | null;
    minAmount?: number | null;
    maxAmount?: number | null;
    issueDateFrom?: string | null;
    issueDateTo?: string | null;
    serviceDateFrom?: string | null;
    serviceDateTo?: string | null;
    isPaid?: boolean | null;
  } = {
    relation: undefined,
    clientId: undefined,
    forwarderId: undefined,
    taxRate: undefined,
    minAmount: undefined,
    maxAmount: undefined,
    issueDateFrom: undefined,
    issueDateTo: undefined,
    serviceDateFrom: undefined,
    serviceDateTo: undefined
  };

  ngOnInit(): void {
    this.loadInvoices();
  }

  public loadInvoices(): void {
    this.isLoading.set(true);

    const issueFrom = this.filters.issueDateFrom ? new Date(this.filters.issueDateFrom) : undefined;
    const issueTo = this.filters.issueDateTo ? new Date(this.filters.issueDateTo) : undefined;
    const serviceFrom = this.filters.serviceDateFrom ? new Date(this.filters.serviceDateFrom) : undefined;
    const serviceTo = this.filters.serviceDateTo ? new Date(this.filters.serviceDateTo) : undefined;

    this.apiClient.getInvoices(
      this.pageNumber(),
      this.pageSize(),
      this.filters.clientId || undefined,
      this.filters.forwarderId || undefined,
      issueFrom,
      issueTo,
      serviceFrom,
      serviceTo,
      this.filters.relation || undefined,
      this.filters.taxRate ?? undefined,
      this.filters.minAmount ?? undefined,
      this.filters.maxAmount ?? undefined
    ).subscribe({
      next: (response) => {
        this.invoices.set(response.items || []);
        this.totalCount.set(response.totalCount || 0);
        this.isLoading.set(false);
      },
      error: (err) => {
        this.notation.apiError(err);
        this.isLoading.set(false);
      }
    });
  }

  public onSearch(): void {
    this.pageNumber.set(1);
    this.loadInvoices();
  }

  public changePage(newPage: number): void {
    if (newPage >= 1 && newPage <= this.totalPagesNumber()) {
      this.pageNumber.set(newPage);
      this.loadInvoices();
    }
  }

  public toggleIsPaidState(): void {
      if (this.filters.isPaid === undefined || this.filters.isPaid === null) {
        this.filters.isPaid = true;
      } else if (this.filters.isPaid === true) {
        this.filters.isPaid = false;
      } else {
        this.filters.isPaid = undefined;
      }
  }

  public onPageSizeChange(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    const size = parseInt(value, 10);
    if (!isNaN(size) && size > 0) {
      this.pageSize.set(size);
      this.pageNumber.set(1);
      this.loadInvoices();
    }
  }
}