import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { AccountService } from '../_services/account.service';
import { validateAllGroupFields } from '../shared/validators/validate';
import { LoginCommand } from '../_services/autogenerated/autogenerated.service';
import { InputComponent } from '../shared/input/input.component';
import { CommonModule } from '@angular/common';
import { TranslatePipe } from '@ngx-translate/core';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss'],
    standalone: true,
    imports: [ReactiveFormsModule, InputComponent, CommonModule, TranslatePipe]
})

export class HomeComponent implements OnInit {
  loginForm!: FormGroup;

  constructor(
    private fb: FormBuilder,
    private accountService: AccountService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.initForm();

    this.accountService.user$.subscribe(user => {
      if (user) {
        this.router.navigateByUrl('/dashboard');
      }
    });
  }

  async onSubmit(): Promise<void> {
    if (!this.loginForm.valid) {
      validateAllGroupFields(this.loginForm);
      return;
    }

    const command: LoginCommand = {
      email: this.loginForm.value.email,
      password: this.loginForm.value.password
    };

    try {
      await firstValueFrom(this.accountService.userLogin(command));
      this.router.navigateByUrl('/dashboard');
    } catch (err) {
      console.error('Login failed', err);
    }
  }

  private initForm(): void {
    this.loginForm = this.fb.group({
      email: [null, [Validators.required, Validators.email]],
      password: [null, [Validators.required]],
    });
  }
}