import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AccountService } from '../_services/account.service';
import { validateAllGroupFields } from '../shared/validators/validate';
import { LoginCommand, UserResponse } from '../_services/autogenerated/autogenerated.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  loginForm: FormGroup = {} as FormGroup;
  user = {} as LoginCommand;
  user$: Observable<UserResponse | null>;
  userData: UserResponse | null = null;
  isTokenValid = false;

  constructor(
    private fb: FormBuilder,
    private accountService: AccountService
  ) {
    this.user$ = this.accountService.user$;
  }

  ngOnInit(): void {
    this.formWrapper();
    this.user$.subscribe(res => {
      this.userData = res;
      this.isTokenValid = true;
    });
  }

  async onSubmit(): Promise<void> {
    if (!this.loginForm.valid) {
      validateAllGroupFields(this.loginForm);
      return;
    }
    
    if (this.loginForm.valid) {
      this.user.Email = this.loginForm.value.login;
      this.user.Password = this.loginForm.value.password;
      await this.accountService.userLogin(this.user);
    }
  }

  formWrapper() {
    this.loginForm = this.fb.group({
      login: [null, [Validators.required]],
      password: [null, [Validators.required]],
    });
  }
}
