import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AccountService } from '../_services/account.service';
import { validateAllGroupFields } from '../shared/validators/validate';
import { UserLoginDTO } from '../_services/autogenerated/autogenerated.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  loginForm: FormGroup;
  user = {} as UserLoginDTO;

  constructor(
    private fb: FormBuilder,
    private accountService: AccountService
  ) {}

  ngOnInit(): void {
    this.formWrapper();
  }

  onSubmit(): void {
    if (!this.loginForm.valid) {
      validateAllGroupFields(this.loginForm);
      return;
    }
    
    if (this.loginForm.valid) {
      this.user.Login = this.loginForm.value.login;
      this.user.Password = this.loginForm.value.password;
      this.user.Prefix = "";
      this.accountService.userLogin(this.user).subscribe(res => {
        
      }, error => {
        console.log(error);
      });
    }

  }

  formWrapper() {
    this.loginForm = this.fb.group({
      login: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
  }
}
