import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { routes } from './app.routes';
import { provideHttpClient, withInterceptors, HttpClient } from '@angular/common/http';
import { errorInterceptor } from './_interceptors/error.interceptor';
import { API_BASE_URL } from './_services/autogenerated/autogenerated.service';
import { environment } from '../environments/environment';
import { jwtInterceptor } from './_interceptors/jwt.interceptor';
import { provideTranslateService, TranslateLoader } from '@ngx-translate/core';
import { Observable } from 'rxjs';

export function createTranslateLoader(http: HttpClient): TranslateLoader {
  return {
    getTranslation: (lang: string): Observable<any> => {
      return http.get(`./assets/i18n/${lang}.json`);
    }
  };
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()), 
    provideHttpClient(
      withInterceptors([errorInterceptor, jwtInterceptor])
    ),
    {
      provide: API_BASE_URL,
      useValue: environment.baseApiUrl
    },
    
    provideTranslateService({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]
      }
    })
  ]
};