import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import {
  CostDetailResponse,
  CostService,
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-cost-list',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslatePipe, RouterLink],
  templateUrl: './cost-list.component.html',
  styleUrls: ['./cost-list.component.scss'],
})
export class CostListComponent implements OnInit {
  private apiClient = inject(CostService);
  private notation = inject(NotificationService);

  public pageNumber = signal<number>(1);
  public pageSize = signal<number>(50);
  public totalCount = signal<number>(0);
  public isLoading = signal<boolean>(false);
  public costs = signal<CostDetailResponse[]>([]);

  public totalPagesNumber = computed(() =>
    Math.max(1, Math.ceil(this.totalCount() / this.pageSize()))
  );

  public filters: {
    searchTerm?: string | null;
    currency?: string | null;
    serviceContractorId?: string | null;
    dateFrom?: string | null;
    dateTo?: string | null;
    isPaid?: boolean | null;
  } = {
    searchTerm: undefined,
    currency: undefined,
    serviceContractorId: undefined,
    dateFrom: undefined,
    dateTo: undefined,
    isPaid: undefined,
  };

  ngOnInit(): void {
    this.loadCosts();
  }

  public loadCosts(): void {
    this.isLoading.set(true);

    const fromDate = this.filters.dateFrom
      ? new Date(this.filters.dateFrom)
      : undefined;
    const toDate = this.filters.dateTo
      ? new Date(this.filters.dateTo)
      : undefined;

    this.apiClient
      .getCosts(
        this.pageNumber(),
        this.pageSize(),
        this.filters.searchTerm || undefined,
        this.filters.currency || undefined,
        this.filters.serviceContractorId || undefined,
        fromDate,
        toDate,
        this.filters.isPaid ?? undefined
      )
      .subscribe({
        next: (response) => {
          this.costs.set(response.items || []);
          this.totalCount.set(response.totalCount || 0);
          this.isLoading.set(false);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isLoading.set(false);
        },
      });
  }

  public onSearch(): void {
    this.pageNumber.set(1);
    this.loadCosts();
  }

  public changePage(newPage: number): void {
    if (newPage >= 1 && newPage <= this.totalPagesNumber()) {
      this.pageNumber.set(newPage);
      this.loadCosts();
    }
  }

  public onPageSizeChange(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    const size = parseInt(value, 10);
    if (!isNaN(size) && size > 0) {
      this.pageSize.set(size);
      this.pageNumber.set(1);
      this.loadCosts();
    }
  }

  public toggleIsPaidState(): void {
    if (this.filters.isPaid === undefined || this.filters.isPaid === null) {
      this.filters.isPaid = true;
    } else if (this.filters.isPaid === true) {
      this.filters.isPaid = false;
    } else {
      this.filters.isPaid = undefined;
    }
  }
}
