import { Component, input, signal, effect, inject, DestroyRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { WorkCaseService, WorkCaseDetailsResponse } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { WorkCaseItemsComponent } from '../work-case-item/work-case-items.component';

@Component({
  selector: 'app-work-case-details',
  standalone: true,
  imports: [CommonModule, TranslatePipe, RouterLink, WorkCaseItemsComponent],
  templateUrl: './work-case-details.component.html',
  styleUrl: './work-case-details.component.scss',
})
export class WorkCaseDetailsComponent {
  private workCaseService = inject(WorkCaseService);
  private notation = inject(NotificationService);
  private destroyRef = inject(DestroyRef);

  id = input.required<string>();
  
  workCase = signal<WorkCaseDetailsResponse | null>(null);
  isLoading = signal<boolean>(false);
  isExpanded = signal<boolean>(true); // Poprawiona literówka nazwy sygnału

  constructor() {
    effect(() => {
      const currentId = this.id();
      if (currentId) {
        this.loadWorkCaseDetails(currentId);
      }
    });
  }

  private loadWorkCaseDetails(caseId: string): void {
    this.isLoading.set(true);
    this.workCaseService.getWorkCaseById(caseId)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => {
          this.workCase.set(data);
          this.isLoading.set(false);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isLoading.set(false);
        }
      });
  }

  togglePanel(): void {
    this.isExpanded.update(state => !state);
  }
}