import { Component, inject, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { catchError, of, tap } from 'rxjs';

import { ServiceContractorResponse, ServiceContractorService } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';

@Component({
  selector: 'app-service-contractor-list-selector',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslatePipe],
  templateUrl: './service-contractors-list-selector.component.html',
  styleUrl: './service-contractors-list-selector.component.scss'
})
export class ServiceContractorListSelectorComponent {
  private apiClient = inject(ServiceContractorService);
  private notation = inject(NotificationService);

  public activeContractor = input<ServiceContractorResponse | null>(null);
  public showAddButton = input<boolean>(true);
  public contractorSelected = output<ServiceContractorResponse>();
  public addRequested = output<void>();

  public contractors = signal<ServiceContractorResponse[]>([]);
  public isLoading = signal<boolean>(false);
  public pageNumber = signal<number>(1);
  public totalPagesNumber = signal<number>(1);
  public pageSize = signal<number>(100);

  public filters = {
    name: '',
    tax: '',
    city: '',
    country: '',
    isActive: undefined as boolean | undefined
  };

  constructor() {
    this.loadContractors();
  }

  public loadContractors() {
    this.isLoading.set(true);
    
    const name = this.filters.name.trim() || undefined;
    const tax = this.filters.tax.trim() || undefined;
    const city = this.filters.city.trim() || undefined;
    const country = this.filters.country.trim() || undefined;
    const isActive = this.filters.isActive ? true : undefined;

    this.apiClient.getServiceContractors(this.pageNumber(), this.pageSize(), name, tax, city, country, isActive)
      .pipe(
        tap(res => {
          this.contractors.set(res.items || []);
          this.isLoading.set(false);
          this.totalPagesNumber.set(res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1);
        }),
        catchError((error) => {
          this.notation.apiError(error);
          this.isLoading.set(false);
          return of({ items: [], totalCount: 0 });
        })
      ).subscribe();
  }

  public onSearch() {
    this.pageNumber.set(1);
    this.loadContractors();
  }

  public changePage(newPage: number) {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadContractors();
  }

  public onPageSizeChange(event: Event) {
    const selectElement = event.target as HTMLSelectElement;
    this.pageSize.set(Number(selectElement.value));
    this.pageNumber.set(1);
    this.loadContractors();
  }

  public selectContractor(contractor: ServiceContractorResponse) {
    this.contractorSelected.emit(contractor);
  }

  public initCreateContractor() {
    this.addRequested.emit();
  }

  public toggleTripleState() {
    if (this.filters.isActive === undefined) {
      this.filters.isActive = true;
    } else if (this.filters.isActive === true) {
      this.filters.isActive = false;
    } else {
      this.filters.isActive = undefined;
    }
  }
}