// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FormupContext))]
    [Migration("20260622191047_TaxAdjustment")]
    partial class TaxAdjustment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Polish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Coutry")
                        .IsRequired()
                        .HasMaxLength(54)
                        .IsUnicode(false)
                        .HasColumnType("varchar(54)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Tax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Models.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("ServiceContractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(7, 3)");

                    b.Property<Guid?>("WorkCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceContractorId");

                    b.HasIndex("WorkCaseId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("Domain.Models.Forwarder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("PassHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varbinary");

                    b.Property<byte[]>("PassSalt")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varbinary");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Forwarders");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Issue_Date");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Service_Date");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(7, 3)");

                    b.Property<Guid?>("WorkCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkCaseId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Models.ServiceContractor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(54)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(54)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ServiceContractors");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<Guid?>("ForwarderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAbandoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ForwarderId");

                    b.ToTable("WorkCases");
                });

            modelBuilder.Entity("Domain.Models.WorkCaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(7, 3)");

                    b.Property<Guid>("WorkCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WorkCaseId");

                    b.ToTable("WorkCaseItems");
                });

            modelBuilder.Entity("Domain.Models.Cost", b =>
                {
                    b.HasOne("Domain.Models.ServiceContractor", "ServiceContractor")
                        .WithMany("Costs")
                        .HasForeignKey("ServiceContractorId")
                        .HasConstraintName("Costs_Service_Contractors");

                    b.HasOne("Domain.Models.WorkCase", "WorkCase")
                        .WithMany("Costs")
                        .HasForeignKey("WorkCaseId")
                        .HasConstraintName("Costs_WorkCases");

                    b.Navigation("ServiceContractor");

                    b.Navigation("WorkCase");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.HasOne("Domain.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("Invoices_Clients");

                    b.HasOne("Domain.Models.WorkCase", "WorkCase")
                        .WithMany("Invoices")
                        .HasForeignKey("WorkCaseId")
                        .HasConstraintName("Invoices_WorkCases");

                    b.Navigation("Client");

                    b.Navigation("WorkCase");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.HasOne("Domain.Models.Client", "Client")
                        .WithMany("WorkCases")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("WorkCases_Clients");

                    b.HasOne("Domain.Models.Forwarder", "Forwarder")
                        .WithMany("WorkCases")
                        .HasForeignKey("ForwarderId")
                        .HasConstraintName("WorkCases_Forwarders");

                    b.Navigation("Client");

                    b.Navigation("Forwarder");
                });

            modelBuilder.Entity("Domain.Models.WorkCaseItem", b =>
                {
                    b.HasOne("Domain.Models.Invoice", "Invoice")
                        .WithMany("WorkCaseItems")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK_WorkCaseItems_Invoices");

                    b.HasOne("Domain.Models.WorkCase", "WorkCase")
                        .WithMany("WorkCaseItems")
                        .HasForeignKey("WorkCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkCaseItems_WorkCases");

                    b.Navigation("Invoice");

                    b.Navigation("WorkCase");
                });

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkCases");
                });

            modelBuilder.Entity("Domain.Models.Forwarder", b =>
                {
                    b.Navigation("WorkCases");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.Navigation("WorkCaseItems");
                });

            modelBuilder.Entity("Domain.Models.ServiceContractor", b =>
                {
                    b.Navigation("Costs");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Invoices");

                    b.Navigation("WorkCaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
