// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FormupContext))]
    partial class FormupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Polish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Coutry")
                        .IsRequired()
                        .HasMaxLength(54)
                        .IsUnicode(false)
                        .HasColumnType("varchar(54)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Tax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TAX");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ZIP");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Models.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tax")
                        .HasColumnType("int")
                        .HasColumnName("TAX");

                    b.Property<Guid?>("WorkCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("WorkCaseId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("Domain.Models.Forwarder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("PassHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varbinary");

                    b.Property<byte[]>("PassSalt")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varbinary");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Forwarders");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("Issue_Date");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("Service_Date");

                    b.Property<int>("Tax")
                        .HasColumnType("int")
                        .HasColumnName("TAX");

                    b.Property<Guid?>("WorkCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkCaseId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amonut")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Tax")
                        .HasColumnType("int")
                        .HasColumnName("TAX");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Domain.Models.ServiceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Coutry")
                        .IsRequired()
                        .HasMaxLength(54)
                        .IsUnicode(false)
                        .HasColumnType("varchar(54)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Tax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TAX");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ZIP");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviders");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ForwardersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ForwardersId");

                    b.ToTable("WorkCases");
                });

            modelBuilder.Entity("Domain.Models.Cost", b =>
                {
                    b.HasOne("Domain.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Costs")
                        .HasForeignKey("ServiceProviderId")
                        .HasConstraintName("Costs_Service_Providers");

                    b.HasOne("Domain.Models.WorkCase", "WorkCase")
                        .WithMany("Costs")
                        .HasForeignKey("WorkCaseId")
                        .HasConstraintName("Costs_WorkCases");

                    b.Navigation("ServiceProvider");

                    b.Navigation("WorkCase");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.HasOne("Domain.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("Invoices_Clients");

                    b.HasOne("Domain.Models.WorkCase", "WorkCase")
                        .WithMany("Invoices")
                        .HasForeignKey("WorkCaseId")
                        .HasConstraintName("Invoices_WorkCases");

                    b.Navigation("Client");

                    b.Navigation("WorkCase");
                });

            modelBuilder.Entity("Domain.Models.Service", b =>
                {
                    b.HasOne("Domain.Models.Invoice", "Invoice")
                        .WithMany("Services")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("Service_Invoices");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.HasOne("Domain.Models.Forwarder", "Forwarders")
                        .WithMany("WorkCases")
                        .HasForeignKey("ForwardersId")
                        .HasConstraintName("WorkCases_Forwarders");

                    b.Navigation("Forwarders");
                });

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Domain.Models.Forwarder", b =>
                {
                    b.Navigation("WorkCases");
                });

            modelBuilder.Entity("Domain.Models.Invoice", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.ServiceProvider", b =>
                {
                    b.Navigation("Costs");
                });

            modelBuilder.Entity("Domain.Models.WorkCase", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
