import { Component, input, signal, inject, effect, DestroyRef } from '@angular/core';
import { CommonModule, DecimalPipe } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { TranslatePipe } from '@ngx-translate/core';

import { NotificationService } from '../../_services/notification.service';
import { 
  WorkCaseService, 
  WorkCaseItemResponse, 
  AddWorkCaseItemCommand, 
  UpdateWorkCaseItemCommand, 
  CostResponse
} from '../../_services/autogenerated/autogenerated.service';
import { InputComponent } from '../input/input.component';

@Component({
  selector: 'app-work-case-items',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslatePipe, DecimalPipe, InputComponent],
  templateUrl: './work-case-items.component.html',
  styleUrl: './work-case-items.component.scss',
})
export class WorkCaseItemsComponent {
  private workCaseService = inject(WorkCaseService);
  private notation = inject(NotificationService);
  private destroyRef = inject(DestroyRef);
  private fb = inject(FormBuilder);

  workCaseId = input.required<string>();

  items = signal<WorkCaseItemResponse[]>([]);
  isLoading = signal<boolean>(false);
  editingItemId = signal<string | null>(null);

  itemForm: FormGroup = this.fb.group({
    name: ['', [Validators.required, Validators.maxLength(150)]],
    amount: [null, [Validators.required, Validators.min(0.01)]],
    invoiceCurrencyCode: ['PLN', [Validators.required]],
    tax: [23, [Validators.required, Validators.min(0)]],
    costAmountNet: [null, [Validators.min(0)]],
    costCurrencyCode: ['PLN']
  });

  constructor() {
    effect(() => {
      const id = this.workCaseId();
      if (id) {
        this.loadItems(id);
      }
    });
  }

  loadItems(id: string): void {
    this.isLoading.set(true);
    this.workCaseService.getItemsForWorkCase(id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => {
          this.items.set(data);
          this.isLoading.set(false);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isLoading.set(false);
        }
      });
  }

  startAdd(): void {
    this.itemForm.reset({ 
      invoiceCurrencyCode: 'PLN', 
      costCurrencyCode: 'PLN', 
      tax: 23 
    });
    this.editingItemId.set('NEW');
  }

  startEdit(item: WorkCaseItemResponse): void {
    if (item.isInvoiced) {
      this.notation.warning('GUI.WORK_CASE_ITEM.CANNOT_EDIT_INVOICED');
      return;
    }

    this.itemForm.patchValue({
      name: item.name,
      amount: item.amountToInvoice,
      invoiceCurrencyCode: item.invoiceCurrencyCode || 'PLN',
      tax: item.tax,
      costAmountNet: item.costAmount,
      costCurrencyCode: item.costCurrencyCode
    });
    
    this.editingItemId.set(item.id!);
  }

  cancelEdit(): void {
    this.editingItemId.set(null);
    this.itemForm.reset();
  }

  saveItem(): void {
    if (this.itemForm.invalid) {
      this.itemForm.markAllAsTouched();
      return;
    }

    this.isLoading.set(true);
    const formValues = this.itemForm.getRawValue();
    const currentEditId = this.editingItemId();

    if (currentEditId === 'NEW') {
      const command: AddWorkCaseItemCommand = {
        workCaseId: this.workCaseId(),
        ...formValues
      };

      this.workCaseService.addItemToWorkCase(command)
        .pipe(takeUntilDestroyed(this.destroyRef))
        .subscribe({
          next: () => this.handleSuccess(),
          error: (err) => this.handleError(err)
        });
    } else {
      const command: UpdateWorkCaseItemCommand = {
        workCaseItemId: currentEditId!,
        ...formValues
      };

      this.workCaseService.updateItemForWorkCase(command)
        .pipe(takeUntilDestroyed(this.destroyRef))
        .subscribe({
          next: () => this.handleSuccess(),
          error: (err) => this.handleError(err)
        });
    }
  }

  deleteItem(id: string): void {
    this.isLoading.set(true);
    this.workCaseService.deleteItemForWorkCase(id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.cancelEdit();
          this.loadItems(this.workCaseId());
        },
        error: (err) => this.handleError(err)
      });
  }

  openCostDetails(costIdOrItemId?: string): void {
    if (!costIdOrItemId) return;
    // TODO: W kolejnym kroku otworzymy tutaj modal lub wyemitujemy event
    console.log('Otwieram Podgląd dla ID:', costIdOrItemId);
  }

  addCostForItem(itemId: string): void {
    // TODO: W kolejnym kroku otworzymy tutaj modal dodawania kosztu
    console.log('Dodaję koszt dla pozycji zlecenia ID:', itemId);
  }

  private handleSuccess(): void {
    this.cancelEdit();
    this.loadItems(this.workCaseId());
  }

  private handleError(err: any): void {
    this.notation.apiError(err);
    this.isLoading.set(false);
  }
}