import { Component, inject, signal, computed, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';

import { 
  ClientService, 
  ClientListItemResponse, 
  CreateClientCommand, 
  UpdateClientCommand 
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { AccountService } from '../../_services/account.service';
import { InputComponent } from '../../shared/input/input.component';
import { ClientListSelectorComponent } from '../client-list-selector/client-list-selector.component';

@Component({
  selector: 'app-clients',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslatePipe, InputComponent, ClientListSelectorComponent],
  templateUrl: './clients.component.html',
  styleUrl: './clients.component.scss'
})
export class ClientsComponent {
  private fb = inject(FormBuilder);
  private apiClient = inject(ClientService);
  private notation = inject(NotificationService);
  private accountService = inject(AccountService);

  @ViewChild(ClientListSelectorComponent) clientListSelector!: ClientListSelectorComponent;

  public selectedClient = signal<ClientListItemResponse | null>(null);
  public isCreateMode = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  
  public canManageCredit = computed(() => {
    return this.accountService.isVerifier() || this.accountService.isManagement();
  });

  public clientForm: FormGroup;

  constructor() {
    this.clientForm = this.fb.group({
      id: [{ value: '', disabled: true }],
      name: ['', Validators.required],
      tax: ['', Validators.required],
      country: ['', Validators.required],
      city: ['', Validators.required],
      zip: ['', Validators.required],
      street: ['', Validators.required],
      houseNumber: ['', Validators.required],
      apartmentNumber: [null],
      email: ['', Validators.email],
      phoneNumber: [''],
      credit: [0, [Validators.required, Validators.min(0)]],
      currency: ['PLN'],
      isActive: [true]
    });
  }

  public selectClient(client: ClientListItemResponse) {
    this.isCreateMode.set(false);
    this.selectedClient.set(client);
    
    this.clientForm.patchValue({
      id: client.id,
      name: client.name,
      tax: client.tax,
      country: client.country,
      city: client.city,
      zip: client.zip,
      street: client.street,
      houseNumber: client.houseNumber,
      apartmentNumber: client.apartmentNumber,
      email: client.email,
      phoneNumber: client.phoneNumber,
      credit: client.credit ?? 0,
      currency: client.currency || 'PLN',
      isActive: client.isActive ?? false
    });

    this.checkCreditAccess();
  }

  public initCreateClient() {
    this.selectedClient.set(null);
    this.isCreateMode.set(true);
    
    this.clientForm.reset({
      id: '',
      name: '',
      tax: '',
      country: '',
      city: '',
      zip: '',
      street: '',
      houseNumber: '',
      apartmentNumber: null,
      email: '',
      phoneNumber: '',
      credit: 0,
      currency: 'PLN',
      isActive: true
    });

    this.checkCreditAccess();
  }

  private checkCreditAccess() {
    const creditControl = this.clientForm.get('credit');
    if (this.canManageCredit()) {
      creditControl?.enable();
    } else {
      creditControl?.disable();
    }
    const currencyControl = this.clientForm.get('currency');
    if (this.canManageCredit()) {
      currencyControl?.enable();
    } else {
      currencyControl?.disable();
    }
  }

  public onSubmit() {
    if (this.clientForm.invalid) return;
    if (!this.isCreateMode() && !this.selectedClient()) return;

    this.isSaving.set(true);
    const formValues = this.clientForm.getRawValue(); 

    if (this.isCreateMode()) {
      const command: CreateClientCommand = {
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber,
        email: formValues.email,
        phoneNumber: formValues.phoneNumber,
        credit: formValues.credit,
        currencyCode: formValues.currency,
        isActive: formValues.isActive
      };

      this.apiClient.createClient(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.isCreateMode.set(false);
          this.clientListSelector.loadClients();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });

    } else {
      const command: UpdateClientCommand = {
        id: this.selectedClient()!.id,
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber,
        email: formValues.email,
        phoneNumber: formValues.phoneNumber,
        credit: formValues.credit,
        currencyCode: formValues.currency,
        isActive: formValues.isActive
      };

      this.apiClient.updateClient(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.clientListSelector.loadClients();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
    }
  }
}