import { Injectable, inject } from '@angular/core';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable, map, of, tap } from 'rxjs';
import { catchError } from 'rxjs/operators';
import {
  AuthService,
  LoginCommand,
  UserResponse,
} from './autogenerated/autogenerated.service';

@Injectable({
  providedIn: 'root',
})
export class AccountService {
  private router = inject(Router);
  private authService = inject(AuthService);

  private userSubject = new BehaviorSubject<UserResponse | null | undefined>(undefined);
  user$: Observable<UserResponse | null | undefined> = this.userSubject.asObservable();

  constructor() {
    this.loadCurrentUser().subscribe();
  }

  userLogin(command: LoginCommand): Observable<UserResponse> {
    return this.authService.login(command).pipe(
      tap((user: UserResponse) => {
        this.setUser(user);
      })
    );
  }

  loadCurrentUser(): Observable<UserResponse | null> {
    const token = localStorage.getItem('token');
    if (!token) {
      this.userSubject.next(null);
      return of(null);
    }

    return this.authService.getCurrentUser().pipe(
      tap((user: UserResponse) => this.userSubject.next(user)),
      catchError(() => {
        this.logout();
        return of(null);
      })
    );
  }

  logout(): void {
    this.userSubject.next(null);
    localStorage.removeItem('token');
    this.router.navigateByUrl('/home');
  }

  private setUser(user: UserResponse): void {
    this.userSubject.next(user);
    if (user?.token?.accessToken) {
      localStorage.setItem('token', user.token.accessToken);
    }
  }
}
