import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable, tap } from 'rxjs';
import {
  UserService,
  LoginCommand,
  UserResponse,
} from './autogenerated/autogenerated.service';

@Injectable({
  providedIn: 'root',
})
export class AccountService {
  private userSubject = new BehaviorSubject<UserResponse | null>(null);
  user$: Observable<UserResponse | null> = this.userSubject.asObservable();

  constructor(
    private router: Router,
    private userService: UserService
  ) {}

  userLogin(command: LoginCommand): Observable<UserResponse> {
    return this.userService.login(command).pipe(
      tap((user: UserResponse) => {
        this.userSubject.next(user);
        localStorage.setItem('token', user.Token.AccessToken);
      })
    );
  }

  logout(): void {
    this.userSubject.next(null);
    localStorage.removeItem('token');
    this.router.navigateByUrl('/home');
  }

  get currentUserValue(): UserResponse | null {
    return this.userSubject.value;
  }
}