import { Component, OnInit } from '@angular/core';
import { BuggyService } from '../../_services/autogenerated/autogenerated.service';

@Component({
  selector: 'app-test-errors',
  templateUrl: './test-errors.component.html',
  styleUrls: ['./test-errors.component.scss'],
  standalone: true,
})
export class TestErrorsComponent implements OnInit {
  validationErrors: string[] = [];

  constructor(private buggyService: BuggyService) {}

  ngOnInit(): void {}

  get401Error() {
    this.buggyService.get401Unauthorized().subscribe({
      error: (err) => console.log('Złapano 401:', err),
    });
  }

  get403Error() {
    this.buggyService.getSecretIfLogged().subscribe({
      error: (err) => console.log('Złapano 403:', err),
    });
  }

  get404Error() {
    this.buggyService.getNotFound().subscribe({
      error: (err) => console.log('Złapano 404:', err),
    });
  }

  get400Error() {
    this.buggyService.getBadRequest().subscribe({
      error: (err) => console.log('Złapano 400:', err),
    });
  }

  get500Error() {
    this.buggyService.getServerError().subscribe({
      error: (err) => console.log('Złapano 500:', err),
    });
  }
}
