import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { WorkCaseResponse, WorkCaseService } from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-work-case-list',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslatePipe, RouterLink],
  templateUrl: './work-case-list.component.html',
  styleUrls: ['./work-case-list.component.scss']
})
export class WorkCaseListComponent implements OnInit {
  private apiClient = inject(WorkCaseService);
  private notation = inject(NotificationService);

  public pageNumber = signal<number>(1);
  public pageSize = signal<number>(50);
  public totalCount = signal<number>(0);
  public isLoading = signal<boolean>(false);
  public workCases = signal<WorkCaseResponse[]>([]);

  public totalPagesNumber = computed(() => Math.max(1, Math.ceil(this.totalCount() / this.pageSize())));

  public filters: {
    name?: string;
    relation?: string;
    forwarderName?: string;
    clientName?: string;
    isAbandoned?: boolean | null;
  } = {
    isAbandoned: undefined
  };

  ngOnInit(): void {
    this.loadWorkCases();
  }

  public loadWorkCases(): void {
    this.isLoading.set(true);

    this.apiClient.getWorkCases(
      this.pageNumber(),
      this.pageSize(),
      this.filters.relation || undefined,
      this.filters.forwarderName || undefined,
      this.filters.clientName || undefined,
      this.filters.name || undefined,
      this.filters.isAbandoned ?? undefined
    ).subscribe({
      next: (response) => {
        this.workCases.set(response.items || []);
        this.totalCount.set(response.totalCount || 0);
        this.isLoading.set(false);
      },
      error: (err) => {
        this.notation.apiError(err);
        this.isLoading.set(false);
      }
    });
  }

  public onSearch(): void {
    this.pageNumber.set(1);
    this.loadWorkCases();
  }

  public changePage(newPage: number): void {
    if (newPage >= 1 && newPage <= this.totalPagesNumber()) {
      this.pageNumber.set(newPage);
      this.loadWorkCases();
    }
  }

  public onPageSizeChange(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    const size = parseInt(value, 10);
    if (!isNaN(size) && size > 0) {
      this.pageSize.set(size);
      this.pageNumber.set(1);
      this.loadWorkCases();
    }
  }

  public toggleTripleState(): void {
    if (this.filters.isAbandoned === undefined || this.filters.isAbandoned === null) {
      this.filters.isAbandoned = false;
    } else if (this.filters.isAbandoned === false) {
      this.filters.isAbandoned = true;
    } else {
      this.filters.isAbandoned = undefined;
    }
  }
}