import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, FormsModule, Validators } from '@angular/forms';
import { catchError, of, tap } from 'rxjs';
import { TranslatePipe } from '@ngx-translate/core';

import { 
  ClientService, 
  ClientListItemResponse, 
  CreateClientCommand, 
  UpdateClientCommand 
} from '../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../_services/notification.service';
import { AccountService } from '../_services/account.service';
import { InputComponent } from '../shared/input/input.component';

@Component({
  selector: 'app-clients',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, TranslatePipe, InputComponent],
  templateUrl: './clients.component.html',
  styleUrl: './clients.component.scss'
})
export class ClientsComponent {
  private fb = inject(FormBuilder);
  private apiClient = inject(ClientService);
  private notation = inject(NotificationService);
  private accountService = inject(AccountService);

  public clients = signal<ClientListItemResponse[]>([]);
  public selectedClient = signal<ClientListItemResponse | null>(null);
  
  public isCreateMode = signal<boolean>(false);
  public isLoading = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  
  public pageNumber = signal<number>(1);
  public totalPagesNumber = signal<number>(1);
  public pageSize = signal<number>(100);

  public canManageCredit = computed(() => {
    return this.accountService.isVerifier() || this.accountService.isManagement();
  });

  public filters = {
    name: '',
    tax: '',
    city: '',
    country: '',
    isActive: undefined as boolean | undefined
  };

  public clientForm: FormGroup;

  constructor() {
    this.clientForm = this.fb.group({
      id: [{ value: '', disabled: true }],
      name: ['', Validators.required],
      tax: ['', Validators.required],
      country: [''],
      city: [''],
      zip: [''],
      street: [''],
      houseNumber: [''],
      apartmentNumber: [null],
      email: ['', Validators.email],
      phoneNumber: [''],
      credit: [0, [Validators.required, Validators.min(0)]],
      currency: ['PLN'],
      isActive: [true]
    });

    this.loadClients();
  }

  public loadClients() {
    this.isLoading.set(true);
    
    const name = this.filters.name.trim() || undefined;
    const tax = this.filters.tax.trim() || undefined;
    const street = undefined;
    const zip = undefined;
    const coutry = this.filters.country.trim() || undefined;
    
    const isActive = (this.filters.isActive === true || this.filters.isActive === false) 
      ? this.filters.isActive 
      : undefined;

    this.apiClient.getClients(tax, name, street, zip, coutry, this.pageNumber(), this.pageSize(), isActive)
      .pipe(
        tap(res => {
          this.clients.set(res.items || []);
          this.isLoading.set(false);
          this.totalPagesNumber.set(res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1);
        }),
        catchError((error) => {
          this.notation.apiError(error);
          this.isLoading.set(false);
          return of({ items: [], totalCount: 0 });
        })
      ).subscribe();
  }

  public onSearch() {
    this.pageNumber.set(1);
    this.loadClients();
  }

  public changePage(newPage: number) {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadClients();
  }

  public onPageSizeChange(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    this.pageSize.set(Number(inputElement.value));
    this.pageNumber.set(1);
    this.loadClients();
  }

  public selectClient(client: ClientListItemResponse) {
    this.isCreateMode.set(false);
    this.selectedClient.set(client);
    
    this.clientForm.patchValue({
      id: client.id,
      name: client.name,
      tax: client.tax,
      country: client.country,
      city: client.city,
      zip: client.zip,
      street: client.street,
      houseNumber: client.houseNumber,
      apartmentNumber: client.apartmentNumber,
      email: client.email,
      phoneNumber: client.phoneNumber,
      credit: client.credit ?? 0,
      currency: client.currency || 'PLN',
      isActive: client.isActive ?? false
    });

    this.checkCreditAccess();
  }

  public initCreateClient() {
    this.selectedClient.set(null);
    this.isCreateMode.set(true);
    
    this.clientForm.reset({
      id: '',
      name: '',
      tax: '',
      country: '',
      city: '',
      zip: '',
      street: '',
      houseNumber: '',
      apartmentNumber: null,
      email: '',
      phoneNumber: '',
      credit: 0,
      currency: 'PLN',
      isActive: true
    });

    this.checkCreditAccess();
  }

  private checkCreditAccess() {
    const control = this.clientForm.get('credit');
    if (this.canManageCredit()) {
      control?.enable();
    } else {
      control?.disable();
    }
  }

  public toggleTripleState() {
    if (this.filters.isActive === undefined) {
      this.filters.isActive = true;
    } else if (this.filters.isActive === true) {
      this.filters.isActive = false;
    } else {
      this.filters.isActive = undefined;
    }
  }

  public onSubmit() {
    if (this.clientForm.invalid) return;
    if (!this.isCreateMode() && !this.selectedClient()) return;

    this.isSaving.set(true);
    const formValues = this.clientForm.getRawValue(); 

    if (this.isCreateMode()) {
      const command: CreateClientCommand = {
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber,
        email: formValues.email,
        phoneNumber: formValues.phoneNumber,
        credit: formValues.credit,
        currency: formValues.currency,
        isActive: formValues.isActive
      };

      this.apiClient.createClient(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.isCreateMode.set(false);
          this.loadClients();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });

    } else {
      const command: UpdateClientCommand = {
        id: this.selectedClient()!.id,
        name: formValues.name,
        tax: formValues.tax,
        country: formValues.country,
        city: formValues.city,
        zip: formValues.zip,
        street: formValues.street,
        houseNumber: formValues.houseNumber,
        apartmentNumber: formValues.apartmentNumber,
        email: formValues.email,
        phoneNumber: formValues.phoneNumber,
        credit: formValues.credit,
        currency: formValues.currency,
        isActive: formValues.isActive
      };

      this.apiClient.updateClient(command).subscribe({
        next: () => {
          this.notation.success('GUI.CONTRACTORS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.loadClients();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
    }
  }
}