import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  FormsModule,
  Validators,
} from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { TranslatePipe } from '@ngx-translate/core';

import {
  UserListItemResponse,
  UpdateUserCommand,
  RegisterUserCommand,
  UserService,
  UserRole,
} from '../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../_services/notification.service';
import { InputComponent } from '../shared/input/input.component';

// Pomocnik do wyciągania ról z Enuma (poza klasą)
const SYSTEM_ROLES = Object.keys(UserRole)
  .filter((key) => isNaN(Number(key)))
  .map((key) => ({
    name: key,
    value: UserRole[key as keyof typeof UserRole],
  }));

@Component({
  selector: 'app-manage-users',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    TranslatePipe,
    InputComponent,
  ],
  templateUrl: './manage-users.component.html',
  styleUrl: './manage-users.component.scss',
})
export class ManageUsersComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly apiClient = inject(UserService);
  private readonly notation = inject(NotificationService);

  public readonly users = signal<UserListItemResponse[]>([]);
  public readonly selectedUser = signal<UserListItemResponse | null>(null);
  public readonly isLoading = signal<boolean>(false);
  public readonly isSaving = signal<boolean>(false);
  public readonly isCreateMode = signal<boolean>(false);

  public readonly pageNumber = signal<number>(1);
  public readonly totalPagesNumber = signal<number>(1);
  public readonly pageSize = signal<number>(100);

  public readonly roles = SYSTEM_ROLES;

  public filters = {
    searchTerm: '',
    role: undefined as UserRole | undefined,
    isActive: undefined as boolean | undefined,
  };

  public readonly userForm: FormGroup = this.fb.group({
    id: [{ value: '', disabled: true }],
    email: ['', [Validators.required, Validators.email]],
    name: ['', Validators.required],
    surname: ['', Validators.required],
    prefix: ['', Validators.required],
    role: [null, Validators.required],
    isActive: [true],
    password: ['', Validators.minLength(6)],
  });

  ngOnInit(): void {
    this.loadUsers();
  }

  public loadUsers(): void {
    this.isLoading.set(true);

    const search = this.filters.searchTerm.trim() || undefined;
    const { role, isActive } = this.filters;

    this.apiClient
      .getUsers(this.pageNumber(), this.pageSize(), search, role as any, isActive)
      .pipe(finalize(() => this.isLoading.set(false)))
      .subscribe({
        next: (res) => {
          this.users.set(res.items || []);
          const totalPages = res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1;
          this.totalPagesNumber.set(totalPages);
        },
        error: (err) => {
          this.notation.apiError(err);
          this.users.set([]);
        },
      });
  }

  public onSearch(): void {
    this.pageNumber.set(1);
    this.loadUsers();
  }

  public changePage(newPage: number): void {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadUsers();
  }

  public onPageSizeChange(event: Event): void {
    const newSize = Number((event.target as HTMLSelectElement).value);
    this.pageSize.set(newSize);
    this.pageNumber.set(1);
    this.loadUsers();
  }

  public toggleTripleState(): void {
    if (this.filters.isActive === undefined) this.filters.isActive = true;
    else if (this.filters.isActive === true) this.filters.isActive = false;
    else this.filters.isActive = undefined;
  }

  public selectUser(user: UserListItemResponse): void {
    this.isCreateMode.set(false);
    this.selectedUser.set(user);
    this.setPasswordValidation({ isRequired: false });

    const matchedRole = this.roles.find((r) => r.name.toLowerCase() === user.role?.toLowerCase());

    this.userForm.patchValue({
      id: user.id,
      email: user.email,
      name: user.name,
      surname: user.surname,
      prefix: user.prefix,
      role: matchedRole ? matchedRole.value : user.role,
      isActive: user.isActive,
      password: '',
    });
  }

  public initCreateUser(): void {
    this.selectedUser.set(null);
    this.isCreateMode.set(true);
    this.setPasswordValidation({ isRequired: true });

    this.userForm.reset({
      id: '',
      email: '',
      name: '',
      surname: '',
      prefix: '',
      role: null,
      isActive: true,
      password: '',
    });
  }

  public onSubmit(): void {
    if (this.userForm.invalid) return;
    if (!this.isCreateMode() && !this.selectedUser()) return;

    this.isSaving.set(true);

    const save$ = this.isCreateMode()
      ? this.apiClient.registerUser(this.buildRegisterPayload())
      : this.apiClient.updateUser(this.buildUpdatePayload());

    save$
      .pipe(finalize(() => this.isSaving.set(false)))
      .subscribe({
        next: () => {
          const msg = this.isCreateMode() ? 'GUI.USERS.CREATE_SUCCESS' : 'GUI.USERS.UPDATE_SUCCESS';
          this.notation.success(msg);
          this.isCreateMode.set(false);
          this.loadUsers();
        },
        error: (err) => this.notation.apiError(err),
      });
  }

  private setPasswordValidation({ isRequired }: { isRequired: boolean }): void {
    const passwordControl = this.userForm.get('password');
    if (!passwordControl) return;

    const validators = isRequired
      ? [Validators.required, Validators.minLength(6)]
      : [Validators.minLength(6)];

    passwordControl.setValidators(validators);
    passwordControl.updateValueAndValidity();
  }

  private buildRegisterPayload(): RegisterUserCommand {
    const val = this.userForm.getRawValue();
    return {
      email: val.email,
      name: val.name,
      surname: val.surname,
      prefix: val.prefix,
      role: Number(val.role),
      password: val.password,
    };
  }

  private buildUpdatePayload(): UpdateUserCommand {
    const val = this.userForm.getRawValue();
    return {
      userId: this.selectedUser()!.id,
      email: val.email,
      name: val.name,
      surname: val.surname,
      prefix: val.prefix,
      role: Number(val.role),
      isActive: val.isActive,
      password: val.password || null,
    };
  }
}