import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  FormsModule,
  Validators,
} from '@angular/forms';
import { catchError, of, tap } from 'rxjs';
import { TranslatePipe } from '@ngx-translate/core';
import {
  UserListItemResponse,
  UpdateUserCommand,
  RegisterUserCommand,
  UserService,
  UserRole,
} from '../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../_services/notification.service';
import { InputComponent } from '../shared/input/input.component';

@Component({
  selector: 'app-manage-users',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    TranslatePipe,
    InputComponent,
  ],
  templateUrl: './manage-users.component.html',
  styleUrl: './manage-users.component.scss',
})
export class ManageUsersComponent {
  private fb = inject(FormBuilder);
  private apiClient = inject(UserService);
  private notation = inject(NotificationService);

  public users = signal<UserListItemResponse[]>([]);
  public selectedUser = signal<UserListItemResponse | null>(null);
  public isLoading = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  public isCreateMode = signal<boolean>(false);

  public pageNumber = signal<number>(1);
  public totalPagesNumber = signal<number>(1);
  public pageSize = signal<number>(100);

  public roles = Object.keys(UserRole)
    .filter((key) => isNaN(Number(key)))
    .map((key) => ({
      name: key,
      value: UserRole[key as keyof typeof UserRole],
    }));

  public filters = {
    searchTerm: '',
    role: undefined as UserRole | undefined,
    isActive: undefined as boolean | undefined,
  };

  public userForm: FormGroup;

  constructor() {
    this.userForm = this.fb.group({
      id: [{ value: '', disabled: true }],
      email: ['', [Validators.required, Validators.email]],
      name: ['',  Validators.required],
      surname: ['', Validators.required],
      prefix: ['', Validators.required],
      role: [null, Validators.required],
      isActive: [true],
      password: ['', Validators.minLength(6)],
    });

    this.loadUsers();
  }

  public loadUsers() {
    this.isLoading.set(true);

    const search = this.searchTerm.trim() || undefined;
    const role = this.filters.role !== undefined ? this.filters.role : undefined;
    const isActive = (this.filters.isActive === true || this.filters.isActive === false) 
      ? this.filters.isActive 
      : undefined;

    this.apiClient.getUsers(this.pageNumber() ,this.pageSize() ,search, role as any, isActive)
      .pipe(
        tap((res) => {
          this.users.set(res.items || []);
          this.isLoading.set(false);
          this.totalPagesNumber.set(
            res.totalCount ? Math.ceil(res.totalCount / this.pageSize()) : 1
          );
        }),
        catchError((error) => {
          this.notation.apiError(error);
          this.isLoading.set(false);
          return of({ items: [], totalCount: 0 });
        })
      )
      .subscribe();
  }

  private get searchTerm(): string {
    return this.filters.searchTerm || '';
  }

  public onSearch() {
    this.pageNumber.set(1);
    this.loadUsers();
  }

  public changePage(newPage: number) {
    if (newPage < 1) return;
    this.pageNumber.set(newPage);
    this.loadUsers();
  }

  public selectUser(user: UserListItemResponse) {
    this.isCreateMode.set(false);
    this.selectedUser.set(user);
    this.userForm.get('password')?.setValidators([Validators.minLength(6)]);
    this.userForm.get('password')?.updateValueAndValidity();
    
    const matchedRole = this.roles.find(r => r.name.toLowerCase() === user.role?.toLowerCase());
    const roleValue = matchedRole ? matchedRole.value : user.role;

    this.userForm.patchValue({
      id: user.id,
      email: user.email,
      name: user.name,
      surname: user.surname,
      prefix: user.prefix,
      role: roleValue,
      isActive: user.isActive,
      password: '',
    });
  }

  public onPageSizeChange(event: Event) {
    const selectElement = event.target as HTMLSelectElement;
    const newSize = Number(selectElement.value);

    this.pageSize.set(newSize);
    this.pageNumber.set(1);
  }

  public initCreateUser() {
    this.selectedUser.set(null);
    this.isCreateMode.set(true);

    this.userForm.reset({
      id: '',
      email: '',
      name: '',
      surname: '',
      prefix: '',
      role: null,
      isActive: true,
      password: '',
    });

    this.userForm.get('password')?.setValidators([Validators.required, Validators.minLength(6)]);
    this.userForm.get('password')?.updateValueAndValidity();
  }

  public toggleTripleState() {
    if (this.filters.isActive === undefined) {
      this.filters.isActive = true;
    } else if (this.filters.isActive === true) {
      this.filters.isActive = false;
    } else {
      this.filters.isActive = undefined;
    }
  }

  public onSubmit() {
    if (this.userForm.invalid) return;
    if (!this.isCreateMode() && !this.selectedUser()) return;

    this.isSaving.set(true);
    const formValues = this.userForm.getRawValue();

    if (this.isCreateMode()) {
      const command: RegisterUserCommand = {
        email: formValues.email,
        name: formValues.name,
        surname: formValues.surname,
        prefix: formValues.prefix,
        role: Number(formValues.role),
        password: formValues.password
      };

      this.apiClient.registerUser(command).subscribe({
        next: () => {
          this.notation.success('GUI.USERS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.isCreateMode.set(false);
          this.loadUsers();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });

    } else {
      const command: UpdateUserCommand = {
        userId: this.selectedUser()!.id,
        email: formValues.email,
        name: formValues.name,
        surname: formValues.surname,
        prefix: formValues.prefix,
        role: Number(formValues.role),
        isActive: formValues.isActive,
        password: formValues.password || null
      };

      this.apiClient.updateUser(command).subscribe({
        next: () => {
          this.notation.success('GUI.USERS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.loadUsers();
        },
        error: (err) => {
          this.notation.apiError(err);
          this.isSaving.set(false);
        }
      });
    }
  }
}
