import { Component, OnInit, inject, signal, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  FormsModule,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';

import {
  ServiceContractorResponse,
  UpdateCostCommand,
  CreateCostCommand,
  CostService,
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { InputComponent } from '../../shared/input/input.component';
import { ServiceContractorListSelectorComponent } from '../../service-contractors/service-contractors-list-selector/service-contractors-list-selector.component';

@Component({
  selector: 'app-cost-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    TranslatePipe,
    InputComponent,
    ServiceContractorListSelectorComponent,
  ],
  templateUrl: './cost-form.component.html',
  styleUrl: './cost-form.component.scss',
})
export class CostFormComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private fb = inject(FormBuilder);
  private costService = inject(CostService);
  private notation = inject(NotificationService);

  @ViewChild(ServiceContractorListSelectorComponent) 
  contractorListSelector!: ServiceContractorListSelectorComponent;

  public workCaseItemId = signal<string | null>(null);
  public costId = signal<string | null>(null);
  public isCreateMode = signal<boolean>(true);

  public selectedContractor = signal<ServiceContractorResponse | null>(null);
  public isLoadingCost = signal<boolean>(false);
  public isSaving = signal<boolean>(false);
  public costForm: FormGroup;

  constructor() {
    this.costForm = this.fb.group({
      name: ['', Validators.required],
      amount: [null, [Validators.required, Validators.min(0.01)]],
      currency: ['PLN', Validators.required],
      tax: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
      issueDate: ['', Validators.required],
      serviceDate: ['', Validators.required],
      isPaid: [false],
      serviceContractorId: [null, Validators.required],
    });
  }

  ngOnInit(): void {
    const cId = this.route.snapshot.paramMap.get('costId');
    const wcItemId = this.route.snapshot.paramMap.get('workCaseItemId');

    if (cId) {
      this.costId.set(cId);
      this.isCreateMode.set(false);
      this.loadCostDetails(cId);
    } else if (wcItemId) {
      this.workCaseItemId.set(wcItemId);
      this.isCreateMode.set(true);

      const today = new Date().toISOString().substring(0, 10);
      this.costForm.patchValue({ issueDate: today, serviceDate: today });
    }
  }

  public selectContractor(contractor: ServiceContractorResponse) {
    this.selectedContractor.set(contractor);
    this.costForm.patchValue({ serviceContractorId: contractor.id });
    this.costForm.get('serviceContractorId')?.markAsTouched();
  }

  public initCreateContractor() {
    // Opcjonalna obsługa, jeśli potrzebujesz zainicjować dodawanie nowego kontrahenta
    // np. otwarcie modala lub nawigacja do formularza kontrahenta
  }

  private loadCostDetails(id: string) {
    this.isLoadingCost.set(true);
    this.costService.getCostById(id).subscribe({
      next: (cost) => {
        const issueDate = cost.issueDate
          ? new Date(cost.issueDate).toISOString().substring(0, 10)
          : '';
        const serviceDate = cost.serviceDate
          ? new Date(cost.serviceDate).toISOString().substring(0, 10)
          : '';

        this.costForm.patchValue({
          name: cost.name,
          amount: cost.amount,
          currency: cost.currency,
          tax: cost.tax,
          issueDate: issueDate,
          serviceDate: serviceDate,
          isPaid: cost.isPaid,
          serviceContractorId: cost.serviceContractorId,
        });

        this.isLoadingCost.set(false);
      },
      error: (err) => {
        this.notation.apiError(err);
        this.isLoadingCost.set(false);
        this.onCancel();
      },
    });
  }

  public onCancel() {
    this.router.navigate(['../..'], { relativeTo: this.route });
  }

  public onSubmit() {
    this.costForm.markAllAsTouched();
    if (this.costForm.invalid) return;

    this.isSaving.set(true);
    const formValues = this.costForm.getRawValue();

    if (this.isCreateMode()) {
      const command: CreateCostCommand = {
        ...formValues,
        workCaseItemId: this.workCaseItemId(),
      };

      this.costService.createCost(command).subscribe({
        next: () => {
          this.notation.success('GUI.COSTS.CREATE_SUCCESS');
          this.isSaving.set(false);
          this.router.navigate(['../../..'], { relativeTo: this.route });
        },
        error: (err) => this.handleError(err),
      });
    } else {
      const command: UpdateCostCommand = {
        id: this.costId()!,
        ...formValues,
        workCaseItemId: this.workCaseItemId(),
      };

      this.costService.updateCost(command).subscribe({
        next: () => {
          this.notation.success('GUI.COSTS.UPDATE_SUCCESS');
          this.isSaving.set(false);
          this.router.navigate(['../../../..'], { relativeTo: this.route });
        },
        error: (err) => this.handleError(err),
      });
    }
  }

  public onDelete() {
    const id = this.costId();
    if (!id) return;

    if (confirm('Czy na pewno chcesz usunąć ten koszt?')) {
      this.isSaving.set(true);
      this.costService.deleteCost(id).subscribe({
        next: () => {
          this.notation.success('GUI.COSTS.DELETE_SUCCESS');
          this.isSaving.set(false);
          this.router.navigate(['../../../..'], { relativeTo: this.route });
        },
        error: (err) => this.handleError(err),
      });
    }
  }

  private handleError(err: any) {
    this.notation.apiError(err);
    this.isSaving.set(false);
  }
}