import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { finalize } from 'rxjs/operators';
import { Observable } from 'rxjs';

import {
  ServiceContractorResponse,
  UpdateCostCommand,
  CreateCostCommand,
  CostService,
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { InputComponent } from '../../shared/input/input.component';
import { ServiceContractorListSelectorComponent } from '../../service-contractors/service-contractors-list-selector/service-contractors-list-selector.component';

interface CostFormState {
  name: FormControl<string>;
  amount: FormControl<number | null>;
  currency: FormControl<string>;
  tax: FormControl<number | null>;
  issueDate: FormControl<string>;
  serviceDate: FormControl<string>;
  serviceContractorId: FormControl<string | null>;
}

@Component({
  selector: 'app-cost-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    TranslatePipe,
    InputComponent,
    ServiceContractorListSelectorComponent,
  ],
  templateUrl: './cost-form.component.html',
  styleUrl: './cost-form.component.scss',
})
export class CostFormComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly location = inject(Location);
  private readonly fb = inject(FormBuilder);
  private readonly costService = inject(CostService);
  private readonly notation = inject(NotificationService);
  private readonly translate = inject(TranslateService);

  public readonly workCaseItemId = signal<string | null>(null);
  public readonly costId = signal<string | null>(null);
  public readonly isCreateMode = signal<boolean>(true);
  public readonly selectedContractor = signal<ServiceContractorResponse | null>(
    null
  );
  public readonly isLoadingCost = signal<boolean>(false);
  public readonly isSaving = signal<boolean>(false);

  public readonly costForm: FormGroup<CostFormState> = this.fb.group({
    name: this.fb.nonNullable.control('', Validators.required),
    amount: this.fb.control<number | null>(null, [
      Validators.required,
      Validators.min(0.01),
    ]),
    currency: this.fb.nonNullable.control('PLN', Validators.required),
    tax: this.fb.control<number | null>(null, [
      Validators.required,
      Validators.min(0),
      Validators.max(100),
    ]),
    issueDate: this.fb.nonNullable.control('', Validators.required),
    serviceDate: this.fb.nonNullable.control('', Validators.required),
    serviceContractorId: this.fb.control<string | null>(
      null,
      Validators.required
    ),
  });

  ngOnInit(): void {
    const workCaseItemId = this.route.snapshot.paramMap.get('itemId');
    const costId = this.route.snapshot.paramMap.get('costId');

    if (costId) {
      this.costId.set(costId);
      this.isCreateMode.set(false);
      this.loadCostDetails(costId);
    } else if (workCaseItemId) {
      this.workCaseItemId.set(workCaseItemId);
      this.isCreateMode.set(true);

      const today = this.formatDateForInput(new Date());
      this.costForm.patchValue({ issueDate: today, serviceDate: today });
    }
  }

  public selectContractor(contractor: ServiceContractorResponse): void {
    this.selectedContractor.set(contractor);
    this.costForm.controls.serviceContractorId.setValue(contractor.id!);
    this.costForm.controls.serviceContractorId.markAsTouched();
  }

  public onCancel(): void {
    this.location.back();
  }

  public onSubmit(): void {
    this.costForm.markAllAsTouched();
    if (this.costForm.invalid || this.isSaving()) return;

    this.isSaving.set(true);
    const formValues = this.costForm.getRawValue();

    let request$: Observable<void>;
    let successMessage: string;

    if (this.isCreateMode()) {
      const createPayload: CreateCostCommand = {
        name: formValues.name,
        amount: formValues.amount,
        currency: formValues.currency,
        tax: formValues.tax,
        issueDate: formValues.issueDate,
        serviceDate: formValues.serviceDate,
        serviceContractorId: formValues.serviceContractorId!,
        workCaseItemId: this.workCaseItemId() || undefined,
        file: null,
        isPaid: false,
      };

      request$ = this.costService.createCost(createPayload);
      successMessage = 'GUI.COSTS.CREATE_SUCCESS';
    } else {
      const updatePayload: UpdateCostCommand = {
        id: this.costId()!,
        file: null,
        amount: formValues.amount,
        currency: formValues.currency,
        tax: formValues.tax,
        name: formValues.name,
        issueDate: formValues.issueDate,
        serviceDate: formValues.serviceDate,
        isPaid: false,
        workCaseItemId: this.workCaseItemId()!,
        serviceContractorId: formValues.serviceContractorId!,
      };

      request$ = this.costService.updateCost(updatePayload);
      successMessage = 'GUI.COSTS.UPDATE_SUCCESS';
    }

    request$.pipe(finalize(() => this.isSaving.set(false))).subscribe({
      next: () => {
        this.notation.success(successMessage);
        this.location.back();
      },
      error: (err) => this.notation.apiError(err),
    });
  }

  public onDelete(): void {
    const id = this.costId();
    if (!id) return;

    const confirmMessage = this.translate.instant('GUI.COSTS.DELETE_CONFIRM');
    if (!confirm(confirmMessage)) return;

    this.isSaving.set(true);
    this.costService
      .deleteCost(id)
      .pipe(finalize(() => this.isSaving.set(false)))
      .subscribe({
        next: () => {
          this.notation.success('GUI.COSTS.DELETE_SUCCESS');
          this.location.back();
        },
        error: (err) => this.notation.apiError(err),
      });
  }

  private loadCostDetails(id: string): void {
    this.isLoadingCost.set(true);
    this.costService
      .getCostById(id)
      .pipe(finalize(() => this.isLoadingCost.set(false)))
      .subscribe({
        next: (cost) => {
          this.costForm.patchValue({
            name: cost.name,
            amount: cost.amount,
            currency: cost.currency,
            tax: cost.tax,
            issueDate: this.formatDateForInput(cost.issueDate),
            serviceDate: this.formatDateForInput(cost.serviceDate),
            serviceContractorId: cost.serviceContractorId,
          });
        },
        error: (err) => {
          this.notation.apiError(err);
          this.onCancel();
        },
      });
  }

  private formatDateForInput(date: Date | string | undefined | null): string {
    if (!date) return '';
    const d = typeof date === 'string' ? new Date(date) : date;
    return isNaN(d.getTime()) ? '' : d.toISOString().substring(0, 10);
  }
}
