import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { finalize, map, switchMap } from 'rxjs/operators';
import { Observable, of } from 'rxjs';

import {
  ServiceContractorResponse,
  UpdateCostCommand,
  CreateCostCommand,
  CostService,
} from '../../_services/autogenerated/autogenerated.service';
import { NotificationService } from '../../_services/notification.service';
import { InputComponent } from '../../shared/input/input.component';
import { ServiceContractorListSelectorComponent } from '../../service-contractors/service-contractors-list-selector/service-contractors-list-selector.component';

function formatDateForInput(date: Date | string | undefined | null): string {
  if (!date) return '';
  const d = typeof date === 'string' ? new Date(date) : date;
  return isNaN(d.getTime()) ? '' : d.toISOString().substring(0, 10);
}

@Component({
  selector: 'app-cost-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    TranslatePipe,
    InputComponent,
    ServiceContractorListSelectorComponent,
  ],
  templateUrl: './cost-form.component.html',
  styleUrl: './cost-form.component.scss',
})
export class CostFormComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly location = inject(Location);
  private readonly fb = inject(FormBuilder);
  private readonly costService = inject(CostService);
  private readonly notation = inject(NotificationService);
  private readonly translate = inject(TranslateService);

  public readonly workCaseItemId = signal<string | null>(null);
  public readonly costId = signal<string | null>(null);
  public readonly isCreateMode = signal<boolean>(true);
  public readonly selectedContractor = signal<ServiceContractorResponse | null>(
    null
  );
  public readonly isLoadingCost = signal<boolean>(false);
  public readonly isSaving = signal<boolean>(false);
  public readonly selectedFile = signal<File | null>(null);

  public readonly costForm = this.fb.group({
    name: ['', Validators.required],
    amount: [<number | null>null, [Validators.required, Validators.min(0.01)]],
    currency: ['PLN', Validators.required],
    tax: [
      <number | null>null,
      [Validators.required, Validators.min(0), Validators.max(100)],
    ],
    issueDate: ['', Validators.required],
    serviceDate: ['', Validators.required],
    serviceContractorId: [<string | null>null, Validators.required],
  });

  ngOnInit(): void {
    const costId = this.route.snapshot.paramMap.get('costId');
    const itemId = this.route.snapshot.paramMap.get('itemId');

    if (costId) {
      this.costId.set(costId);
      this.isCreateMode.set(false);
      this.loadCostDetails(costId);
    }
    if (itemId) {
      this.workCaseItemId.set(itemId);
      const today = formatDateForInput(new Date());
      this.costForm.patchValue({ issueDate: today, serviceDate: today });
    }
  }

  public selectContractor(contractor: ServiceContractorResponse): void {
    this.selectedContractor.set(contractor);
    this.costForm.patchValue({ serviceContractorId: contractor.id! });
    this.costForm.controls.serviceContractorId.markAsTouched();
  }

  public onFileSelected(event: Event): void {
    const files = (event.target as HTMLInputElement).files;
    this.selectedFile.set(files?.length ? files[0] : null);
  }

  public onSubmit(): void {
    this.costForm.markAllAsTouched();
    if (this.costForm.invalid || this.isSaving()) return;

    this.isSaving.set(true);

    const saveCost$ = this.isCreateMode()
      ? this.costService.createCost(this.buildCreatePayload())
      : this.costService
          .updateCost(this.buildUpdatePayload())
          .pipe(map(() => this.costId()!));

    saveCost$
      .pipe(
        switchMap((costId) => this.uploadFileIfPresent(costId)),
        finalize(() => this.isSaving.set(false))
      )
      .subscribe({
        next: () => {
          const msg = this.isCreateMode()
            ? 'GUI.COSTS.CREATE_SUCCESS'
            : 'GUI.COSTS.UPDATE_SUCCESS';
          this.notation.success(msg);
          this.onCancel();
        },
        error: (err) => this.notation.apiError(err),
      });
  }

  public onDelete(): void {
    const id = this.costId();
    if (!id || !confirm(this.translate.instant('GUI.COSTS.DELETE_CONFIRM')))
      return;

    this.isSaving.set(true);
    this.costService
      .deleteCost(id)
      .pipe(finalize(() => this.isSaving.set(false)))
      .subscribe({
        next: () => {
          this.notation.success('GUI.COSTS.DELETE_SUCCESS');
          this.onCancel();
        },
        error: (err) => this.notation.apiError(err),
      });
  }

  public onCancel(): void {
    this.location.back();
  }

  private uploadFileIfPresent(costId: string): Observable<unknown> {
    const file = this.selectedFile();
    if (!file || !costId) return of(null);

    return this.costService.uploadCostFile(costId, {
      data: file,
      fileName: file.name,
    });
  }

  private buildCreatePayload(): CreateCostCommand {
    const val = this.costForm.getRawValue();
    return {
      name: val.name!,
      amount: val.amount!,
      currency: val.currency!,
      tax: val.tax!,
      issueDate: val.issueDate!,
      serviceDate: val.serviceDate!,
      serviceContractorId: val.serviceContractorId!,
      workCaseItemId: this.workCaseItemId()!,
      isPaid: false,
    };
  }

  private buildUpdatePayload(): UpdateCostCommand {
    const val = this.costForm.getRawValue();
    return {
      id: this.costId()!,
      name: val.name!,
      amount: val.amount!,
      currency: val.currency!,
      tax: val.tax!,
      issueDate: val.issueDate!,
      serviceDate: val.serviceDate!,
      serviceContractorId: val.serviceContractorId!,
      workCaseItemId: this.workCaseItemId()!,
      isPaid: false,
    };
  }

  private loadCostDetails(id: string): void {
    this.isLoadingCost.set(true);
    this.costService
      .getCostById(id)
      .pipe(finalize(() => this.isLoadingCost.set(false)))
      .subscribe({
        next: (cost) => {
          this.costForm.patchValue({
            name: cost.name,
            amount: cost.amount,
            currency: cost.currency,
            tax: cost.tax,
            issueDate: formatDateForInput(cost.issueDate),
            serviceDate: formatDateForInput(cost.serviceDate),
            serviceContractorId: cost.serviceContractorId,
          });
          if (cost.serviceContractorResponse) {
            this.selectContractor(cost.serviceContractorResponse)
          }
        },
        error: (err) => {
          this.notation.apiError(err);
          this.onCancel();
        },
      });
  }
}
